# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: localhost:3000
  secret_key_base: 39da44fbfd4313210930199c92953f09bbc3c78eedef2ee4f3aeb433fa19a90c64fb7f52f7871e77efdf88e15807c78d52e3d1c89f0dd9b9b3fec726b7d2d0af
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>

test:
  domain_name: example.com 
  secret_key_base: e6449cb4b17a989fee36b120f10a7cc92d2b0ae4f7217c4ee34693a35cf7cf4d22b58a59b943c2abeba2324213c01b8aa0c6e1f4f96b601b275684be976cfe08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
